// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-skills.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var search_skills_default = defineTool({
  name: "search_skills",
  title: "Search skills",
  description: "Search or browse published real estate AI skills in the RealToolbox.ai library. Returns skill metadata (name, slug, tagline, tier, access_level, price). Use get_skill to retrieve full content for a specific skill.",
  inputSchema: {
    query: z.string().optional().describe("Optional search text matched against skill name, tagline, and description."),
    tier: z.string().optional().describe("Optional tier filter (e.g. 'free', 'pro')."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, tier, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("skills").select("slug,name,tagline,description,tier,access_level,price,download_count").eq("is_published", true).order("sort_order", { ascending: true }).limit(limit ?? 20);
    if (tier) q = q.eq("tier", tier);
    if (query && query.trim()) {
      const t = query.trim();
      q = q.or(`name.ilike.%${t}%,tagline.ilike.%${t}%,description.ilike.%${t}%`);
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { skills: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-skill.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function adminClient() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
function userClient(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function requiredToolboxFor(skillToolbox) {
  if (skillToolbox === "investor") return "investor_toolbox";
  if (skillToolbox === "agent") return "agent_toolbox";
  return null;
}
function pathFromFileUrl(fileUrl) {
  const m = fileUrl.match(/\/skill-files\/(.+)$/);
  return m ? decodeURIComponent(m[1]) : null;
}
var get_skill_default = defineTool2({
  name: "get_skill",
  title: "Get skill",
  description: "Fetch a full skill by slug. Metadata and `overview` (marketing description) are public. For entitled callers (free skills, or paid skills where the signed-in user has purchased the matching toolbox or the Complete Toolbox), the actual skill markdown is returned in `content`. Otherwise `content` is omitted and a `locked` flag is set.",
  inputSchema: {
    slug: z2.string().min(1).describe("The skill slug, e.g. 'deal-screen'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    const supabase = adminClient();
    const { data: skill, error } = await supabase.from("skills").select("slug,name,tagline,description,tier,access_level,price,overview,toolbox,file_url").eq("slug", slug).eq("is_published", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!skill) return { content: [{ type: "text", text: `No skill with slug '${slug}'.` }], isError: true };
    const isPaid = skill.access_level === "paid";
    const requiredToolbox = requiredToolboxFor(skill.toolbox);
    let unlocked = !isPaid;
    if (isPaid && requiredToolbox && ctx.isAuthenticated()) {
      const { data: purchases } = await userClient(ctx).from("purchases").select("toolbox_slug, status").eq("user_id", ctx.getUserId()).eq("status", "paid");
      const owned = new Set((purchases ?? []).map((p) => p.toolbox_slug));
      unlocked = owned.has("complete_toolbox") || owned.has(requiredToolbox);
    }
    const { file_url, ...meta } = skill;
    let payload;
    if (unlocked) {
      let content = null;
      let content_error = null;
      const path = file_url ? pathFromFileUrl(file_url) : null;
      if (!file_url) {
        content_error = "no_file";
      } else if (!path) {
        content_error = "bad_file_url";
      } else {
        const { data: blob, error: dlErr } = await adminClient().storage.from("skill-files").download(path);
        if (dlErr || !blob) {
          content_error = "download_failed";
        } else {
          content = await blob.text();
        }
      }
      payload = { ...meta, content, ...content_error ? { content_error } : {} };
    } else {
      payload = {
        ...meta,
        locked: true,
        required_toolbox: requiredToolbox,
        unlock_hint: "Requires a one-time toolbox purchase. Sign in and buy the matching Toolbox at https://realtoolbox.ai to unlock."
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-integrations.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_integrations_default = defineTool3({
  name: "list_integrations",
  title: "List integrations",
  description: "List published integrations in the RealToolbox.ai directory (MCP servers and other tools that connect AI assistants to real estate workflows). Optionally filter by category.",
  inputSchema: {
    category: z3.string().optional().describe("Optional category slug: property-data, crm, communication, productivity, content-creation, automation, developer.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("integrations").select("name,slug,tagline,category,difficulty,setup_url").eq("is_published", true).order("sort_order", { ascending: true });
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { integrations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-purchases.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_my_purchases_default = defineTool4({
  name: "get_my_purchases",
  title: "Get my purchases",
  description: "Return the signed-in user's RealToolbox.ai toolbox purchases (owned toolboxes and purchase history). Requires an authenticated caller.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_ANON_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("purchases").select("toolbox_slug, status, purchased_at").eq("user_id", ctx.getUserId()).eq("status", "paid");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const purchases = data ?? [];
    const owned_toolboxes = purchases.map((p) => p.toolbox_slug);
    const payload = { owned_toolboxes, purchases };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pcnsuyadfqrmythikwpa";
var mcp_default = defineMcp({
  name: "realtoolbox-mcp",
  title: "RealToolbox.ai",
  version: "0.2.0",
  instructions: "Tools for RealToolbox.ai \u2014 a curated library of AI skills and integrations for real estate investors and the agents who serve them. Skills are unlocked by one-time Toolbox purchases: the Investor Toolbox (every investor skill), or the Complete Toolbox (every investor skill, plus the Scaling Toolbox free when it releases). Use search_skills to browse the skill library, get_skill to retrieve a specific skill's full content (paid skills require the matching toolbox purchase on the caller's account), list_integrations to browse integration directory entries, and get_my_purchases to check the signed-in user's owned toolboxes.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_skills_default, get_skill_default, list_integrations_default, get_my_purchases_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
